name: Build and Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_package:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python & pip
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '>=3.11 <=3.12'
        cache: 'pip'

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1
      with:
        version: 2.1.*

    - name: Get Conan cache location
      if: runner.os == 'Windows'
      id: conan-cache-location
      run: |
        $cacheLocation = conan config home | Out-String
        Write-Host "::set-output name=cache-location::$cacheLocation"
        
    - name: Cache Conan packages
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: ${{ steps.conan-cache-location.outputs.cache-location }}
        key: ${{ matrix.os }}-${{ matrix.build_type }}-conan-${{ hashFiles('Source/Projects.py') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.build_type }}-conan-

    - name: get-cmake
      uses: lukka/get-cmake@v3.29.3
      with:
        cmakeVersion: "^3.25.0"

    - name: Conan Profile Detect
      run: conan profile detect --force

    - name: Setup.py (${{ matrix.build_type }})
      run: python Setup.py -c ${{ matrix.build_type }}

    - name: Setup MSBuild
      if: runner.os == 'Windows'
      uses: microsoft/setup-msbuild@v1

    - name: Build Source.sln (${{ matrix.build_type }})
      if: runner.os == 'Windows'
      run: |
        msbuild Generated/CMake_${{ matrix.build_type }}/Source.sln /p:Configuration=${{ matrix.build_type }} /p:Platform="x64"
      env:
        SolutionPath: Generated/CMake_${{ matrix.build_type }}/Source.sln
        Configuration: ${{ matrix.build_type }}

    - name: Create archives (windows)
      if: github.event_name == 'workflow_dispatch' && runner.os == 'Windows' # we only create packages when manually running
      run: |
        $basePath = "Generated/Packages"
        $projects = Get-ChildItem -Path $basePath -Directory
        foreach ($project in $projects) {
            $projName = $project.Name
            $packagePath = Join-Path -Path $basePath -ChildPath $projName ${{ matrix.build_type }}
            $outputPath = "$projName.${{ matrix.build_type }}.zip"
            Compress-Archive -Path "$packagePath/*" -DestinationPath $outputPath -CompressionLevel Optimal 
            Write-Host "Packaged $packagePath into $outputPath"
        }

    - name: Create archives (unix)
      if: github.event_name == 'workflow_dispatch' && runner.os != 'Windows' # we only create packages when manually running
      run: |
        basePath="Generated/Packages"
        projects=$(find "$basePath" -mindepth 1 -maxdepth 1 -type d)
        for project in $projects; do
            projName=$(basename "$project")
            packagePath="$basePath/$projName/${{ matrix.build_type }}"
            outputPath="$projName.${{ matrix.build_type }}.zip"
            zip -r "$outputPath" "$packagePath"
            echo "Packaged $packagePath into $outputPath"
        done

    - name: Upload package artifacts
      if: github.event_name == 'workflow_dispatch' # we only create packages when manually running
      uses: actions/upload-artifact@v4
      with:
        path: '*.zip'
        if-no-files-found: error
        # No compression, the packages are already compressed
        # We may wish to improve the compression in the Create archives step later.
        compression-level: 0
        # Shorten the retention days. We do not use GitHub for hosting important artifacts.
        # Download your artifacts and retain them in our build server and/or releases tab.
        retention-days: 30